language: ruby
#cache: bundler
gemfile: Gemfile
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.3.7

 install: gem install jekyll -v 2.4.0 && gem install s3_website

 script: jekyll build

 after_success: s3_website push
